# config/config.yaml

# global
global:
  max_goroutines: 5 # 동시 실행 가능한 로그 감시 고루틴 최대 개수.
  cpu_limit_percent: 80 # CPU 사용량 상한 (고민 필요).
  memory_limit_mb: 512 # 메모리 사용량 상한 (고민 필요).
  event_tcp_enabled: true # TCP 이벤트 전송 활성화 여부.
  event_tcp_address: "127.0.0.1:9000" # 이벤트 전송할 TCP 주소.
  default_compress: false # 기본 저장 파일 압축 여부.
  default_save_path: "/tmp/tracklog_output" # 추출 로그 기본 저장 경로.

# monitors
monitors:
  - name: "tracklog_test" # 이 감시 설정의 고유 이름. (key)
    path: "/tmp" # 로그 파일 디렉토리 경로.
    filename_pattern: "tracklog_test.log" # 감시할 로그 파일명. (파일 이름도 나중엔 정규식 + 배열처리 해야겠다)
    extract_type: "regex" # 추출 방식 (regex 또는 plain).
    extract_pattern: "(INFO|Warning|ERROR)" # 추출 패턴 (정규식 또는 문자열).
    save_extracted: true # 추출된 로그 저장 여부.
    save_path: "/tmp/tracklog_output/test.log" # 추출 로그 저장 경로.
    compress_output: false # 추출 로그 압축 여부.
    realtime: true # 실시간 감시 여부.
    event_on_no_update: true # 로그 업데이트 없으면 이벤트 발생 여부.
    event_tcp_enabled: true # TCP 이벤트 전송 여부.